### ISSUE TITLE
右侧导航栏中没必要显示所有的评论信息

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#10]
这样的显示就太长了，可以适当截取

暂时无法上传图片，具体问题就是把下面的回复都显示在右侧了。
http://inchina.xin:8000/topic/1001/#reply2004

**Comment by insionng** [comment]
第2版本的时候是正常的，但由于新版需要支持视频等等富媒体的展示，改版过程中没法照顾到所有地方，所有临时全部展示出来，因为截取很容易导致html截取不完整，导致因为发了个评论或话题而导致整个网站布局因为元素错乱导致渲染html错误。

这些在后面我会补回来。

**Comment by insionng** [comment]
已经修复～
