### ISSUE TITLE
增加回复可见功能

### ISSUE THREAD

**Issue by insionng** [insionng/yougam#11]

**Comment by laofo** [comment]
现在全站开启这个功能了么？为什么我自己回复你的，我自己都看不到了。。。

**Comment by laofo** [comment]
http://inchina.xin:8000/topic/6001/ 这个帖子下，我回复了几次，但是现在都看不到我自己的回复

**Comment by insionng** [comment]
@laofo 这问题是由于昨天更新代码引入的，现在已经修正，感谢反馈.

**Comment by insionng** [comment]
已经支持，发布新帖的时候选 回复收费 类型即可～
