### ISSUE TITLE
技术改进：选择节点位置不明显

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#2]
![default](https://cloud.githubusercontent.com/assets/46148/14466281/b1e3d198-0108-11e6-8de6-74923fab64b7.png)

按照我的操作习惯：当写完题目和正文后，我就立刻看到了左下角的#提交# 按钮。根本没去看，也不注意右下角还有个节点选择按钮。（因为按照正常人的逻辑，当我看到提交按钮后，点击完，就觉得不应该还有其他操作。

不应该期待看到用户在提交后，再去选择节点。

建议：节点选择按钮放到左上角题目上方。提交按钮放到右下角。

可参考下面的例子

![default](https://cloud.githubusercontent.com/assets/46148/14466396/3af682e6-0109-11e6-87cd-e35ce22c3199.PNG)

**Comment by insionng** [comment]
好的，这个地方我会尝试改进呈现的形式~

**Comment by insionng** [comment]
已经修改～
