### ISSUE TITLE
话题类别（话题种类探讨）

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#20]
优选话题 新鲜话题 热辣话题 话题趋势 高分话题 高票话题 热议话题 流行话题 冷门话题 话题收藏

这么多分类其实区别没那么大，反而看了头晕。进入一个节点，我作为用户比较关注的话题类别有：

1. 最新的被回复的话题：按照被回复时间排列。这个一般都是默认排序。
2. 最新的话题：最新的发出来的话题，按照话题的时间排列（类似BBS上的同主题模式）
3. 热贴：热门的话题，讨论的最多。这个可以让用户点一下然后排列展示
4. 精华贴 vs 收藏的话题：精华贴类似收藏的话题。但是这个收藏的话题有很大的不一样。

 - 收藏的话题，为用户觉得这个话题有价值，所以用户收藏起来（关注的话题）日后看看别人是否回复；
  - 而精话贴则为这个节点的管理员觉得这个帖子很有价值。相当于管理员对帖子进行标记，希望用户重点看的内容。
两种的思路根本就是不同的。

@insionng 考虑一下，看看哪几种是用户最想要的。可以把前四类放到默认展示，其他放到更多里，可能更好。

![image](https://cloud.githubusercontent.com/assets/46148/14744105/e4d26a48-08d7-11e6-98d1-0611930c1659.png)

**Comment by insionng** [comment]
之所以有这么多种类别，是因为这些都是YOUGAM项目最开始的时候为了研究算法排序的各种优劣表现力，所以这个是不会移除的。用的时候如果实在不需要有这么多功能可以自行修改模板屏蔽掉这些分类方式～

**Comment by insionng** [comment]
而且，很多时候用户自己并不一定清楚知道自己需要什么， 最好的做法是人工筛选，其次是靠算法自动推荐。

**Comment by laofo** [comment]
研究算法优劣.....

**Comment by insionng** [comment]
当时主要是为了观察reddit的各种算法在数据小和大时表现出来的排序效果，哪个推荐出来的内容更有意思～
