### ISSUE TITLE
页面间隔不统一

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#42]
置顶的两个帖子所占的面积和下面正常的两个帖子占的面积不等。

看上去不太协调

不是大问题，可以后续调整

**Comment by insionng** [comment]
主要是为了色彩高亮和区分，置顶的有独立的边距。

**Comment by laofo** [comment]
色彩高亮很不错。但是独立的边距其实没太大必要。反而不协调。
当然你也可以考虑在置顶的主题边边上显示个置顶的小图标。（不过这个不重要）
重要的的是边距最好要统一。

**Comment by insionng** [comment]
好像有点道理，我修改下看看效果如何～

**Comment by insionng** [comment]
http://www.yougam.com/  置顶栏位的边距去掉了，效果看起来貌似还行，采纳建议！

**Comment by laofo** [comment]
效果不错，感谢采纳
