### ISSUE TITLE
YOUGAM迁移数据到V3后帖子时间显示问题

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#44]
所有的帖子都变成了统一的一个时间点。之前的发帖时间丢失了？

小问题。

**Comment by insionng** [comment]
我导入时图方便统一使用了现在的时间，这不是很重要。

**Comment by laofo** [comment]
对于大站点有时还是有必要的。比如一个网站建立10年了，现在要查查当时的一些数据，如果时间都被更新了，很多日后的数据统计就都没法做了。

大站变更建站系统之所以难，就难在数据转换上。很多历史数据在那。当然也这是大站的价值所在。

**Comment by insionng** [comment]
嗯，以后写转换程序的时候会注意。
