### ISSUE TITLE
手机浏览器访问样式错乱

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#49]

**Comment by insionng** [comment]
你是神马手机、神马浏览器？如果手机浏览器支持标准的话 应该是不会乱的，不过后续在手机端主要以app客户端来实现支持为主，web端主要照顾pc。

**Comment by laofo** [comment]
iphone5s ios 9.3.1 safari

**Comment by laofo** [comment]
你要是手机端都用app支持，那android 和 ios 都要单独做。工作量不小。考虑下h5？

**Comment by laofo** [comment]
![qq 20160527231525](https://cloud.githubusercontent.com/assets/46148/15612350/080d26f2-2461-11e6-97f9-14639616503a.jpg)

**Comment by insionng** [comment]
这其实并没有乱啊，只是内容稍多，行距被增多了罢了～

**Comment by laofo** [comment]
多少个PV，多少个协程，版权声明这段。明显影响了主题阅读功能。

可以考虑移动端省去。或者精简成一行。

**Comment by insionng** [comment]
好
