### ISSUE TITLE
FR:发送随机密码功能

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#5]
经常遇到的一个问题是，用户忘记用户名了，也不清楚自己用的哪个邮箱注册的了。把好几个邮箱发了过来，希望重置密码。这个时候，如果这里有个**发送重置密码**的功能就太好了。指接把一个随机的密码发送到她的邮箱里边。省去了每次还要给他们重置一个弱密码，还要明文发给他们。

![default](https://cloud.githubusercontent.com/assets/46148/14467461/069d3ddc-010e-11e6-8e72-22a32eee3391.PNG)

**Comment by insionng** [comment]
问题是，不需要验证用户吗？直接把重置链接发到他邮箱？还是说，这个功能只对管理员可见？

**Comment by laofo** [comment]
这个是后台的用户列表，是指对管理员可见的。发送到用户注册邮箱里去，不会产生问题。

**Comment by insionng** [comment]
如果是这样的话，这个功能是可以加上的。

**Comment by insionng** [comment]
现在已经支持此功能，问题关闭～
