### ISSUE TITLE
帖子置顶功能

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#7]
有把某个贴子置顶到本节点的最上边么？让人一进这个节点就可以看到这个帖子。

**Comment by laofo** [comment]
这个功能是最好有，没有也可以接受。

目的是想有一种机制可以让某些贴子就像某些节点一样让大家先看看。

**Comment by insionng** [comment]
人工干预+算法计算，人工优先。

**Comment by laofo** [comment]
GOOD
