### ISSUE TITLE
精华帖子功能

### ISSUE THREAD

**Issue by laofo** [insionng/yougam#8]
其实就是有很多主题都非常不错，希望日后可以通过某种手段搜索到。

discuz 是把精华帖子放到一个节点的下边。有个按钮一点精华，就把这个节点下精华的帖子都列出来了。

而ruby-china，是把全站点赞人数超过5的帖子进行了索引放到了首页
https://ruby-china.org/topics/popular

其实这两种功能都是有必要的，可以结合到一起使用。节点内的精华文章可以自动推送到（或者通过设置）放到网站首页，让更多的人看到，形成更大的热点。

**Comment by insionng** [comment]
这个可以有，我会加上。

**Comment by insionng** [comment]
现在采用算法自动计算出的优选话题即是精华帖子，置顶采取人工干预。
